stages:
  - mirror

mirror_to_github:
  stage: mirror
  image: alpine:latest
  before_script:
    - apk add --no-cache git openssh
    - git config --global user.name "Your Name"
    - git config --global user.email "your.email@example.com"
  script:
    - git clone --mirror "$CI_REPOSITORY_URL" repo.git
    - cd repo.git
    - git remote set-url --push origin "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/trevin-lee/jupyter-kube.git"
    - git push --mirror
  only:
    - main  # change this if your branch is named differently
